# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
      displayName: 'Use .Net 8 SDK.'
      
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
      displayName: 'Restore packages.'
      
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
      displayName: 'Run tests.'
